name: Pull Request Branch Policies

on:
  pull_request:
    branches:
      - master
      - release/*
    types:
      - opened
      - synchronize
      - reopened

jobs:
  validation_branch_rules:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch rules
        run: |
          TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"  # La rama a la que se hace el PR (target)
          SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"  # La rama desde la que se hace el PR (source)

          # Validar PRs a la rama master
          if [[ "$TARGET_BRANCH" == "master" ]]; then
            if [[ "$SOURCE_BRANCH" != release/* ]]; then
              echo "Pull requests to master can only be made from release/* branches."
              exit 1
            fi
          fi

          # Validar PRs a ramas release/*
          if [[ "$TARGET_BRANCH" == release/* ]]; then
            if [[ "$SOURCE_BRANCH" != feature/* && "$SOURCE_BRANCH" != fix/* ]]; then
              echo "Pull requests to release/* branches can only be made from feature/* or fix/* branches."
              exit 1
            fi
          fi
