name: Tag Release on Merge

on:
  push:
    branches:
      - master

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if last merged branch was a release/*
        id: check_release_branch
        run: |
          LAST_COMMIT=$(git log -1 --pretty=%B)
          echo "Last commit message: $LAST_COMMIT"
          if [[ "$LAST_COMMIT" == *"Merge pull request"*release/* ]]; then
            echo "Merged from release branch"
            echo "release=true" >> $GITHUB_ENV
          else
            echo "Not merged from a release branch"
            echo "release=false" >> $GITHUB_ENV
          fi

      - name: Extract release version from branch name
        id: extract_version
        if: env.release == 'true'
        run: |
          RELEASE_BRANCH="${GITHUB_REF##*/}"
          echo "Release branch: $RELEASE_BRANCH"
          echo "version=$RELEASE_BRANCH" >> $GITHUB_ENV

      - name: Create Git tag
        if: env.release == 'true'
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag ${{ env.version }}
          git push origin ${{ env.version }}
