name: Tag Release on Merge

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  create_tag_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if branch is a release branch
        id: check_release_branch
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          echo "Branch name: $BRANCH_NAME"
          if [[ "$BRANCH_NAME" == release/* ]]; then
            VERSION="${BRANCH_NAME#release/}"
            TAG="v$VERSION"
            echo "release=true" >> $GITHUB_ENV
            echo "version=$TAG" >> $GITHUB_ENV
          else
            echo "release=false" >> $GITHUB_ENV
          fi

      - name: Create Git tag
        if: env.release == 'true'
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag ${{ env.version }}
          git push origin ${{ env.version }}

      - name: Notify Packagist
        run: |
          curl -X POST "https://packagist.org/api/update-package?username=jospina_apptank&apiToken=${{secrets.PACKAGIST_TOKEN}}"

      - name: Create GitHub Release
        if: env.release == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: ${{ env.version }}
          draft: false
          prerelease: false
