name: Tag Release on Merge

on:
  push:
    branches:
      - master

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if last merged branch was a release/*
        id: check_release_branch
        run: |
          LAST_COMMIT=$(git log -1 --pretty=%B)
          echo "Last commit message: $LAST_COMMIT"
          if [[ "$LAST_COMMIT" == *"Merge pull request"*release/* ]]; then
            echo "Merged from release branch"
            echo "::set-output name=release::true"
          else
            echo "Not merged from a release branch"
            echo "::set-output name=release::false"
          fi

    # Continue only if the merge was from a release/* branch
    if: steps.check_release_branch.outputs.release == 'true'

    steps:
      - name: Extract release version from branch name
        id: extract_version
        run: |
          RELEASE_BRANCH="${GITHUB_REF##*/}"
          echo "Release branch: $RELEASE_BRANCH"
          echo "::set-output name=version::$RELEASE_BRANCH"

      - name: Create Git tag
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag ${{ steps.extract_version.outputs.version }}
          git push origin ${{ steps.extract_version.outputs.version }}
