name: Tag Release on Merge

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate and extract release branch
        id: check_release_branch
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          echo "Branch name: $BRANCH_NAME"
          if [[ "$BRANCH_NAME" == release/* ]]; then
            echo "release=true" >> $GITHUB_ENV
            echo "version=$BRANCH_NAME" >> $GITHUB_ENV
          else
            echo "release=false" >> $GITHUB_ENV
          fi

      - name: Create Git tag
        if: env.release == 'true'
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag ${{ env.version }}
          git push origin ${{ env.version }}
